package model;

import java.io.Serializable;

/**
 * Model class of categorias.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Categorias implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** categoria. */
	private String categoria;

	/** descripcion. */
	private String descripcion;

	/**
	 * @param id
	 * @param categoria
	 * @param descripcion
	 */
	public Categorias(Integer id, String categoria, String descripcion) {
		super();
		this.id = id;
		this.categoria = categoria;
		this.descripcion = descripcion;
	}

	/**
	 * Set the id.
	 * 
	 * @param id id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the categoria.
	 * 
	 * @param categoria categoria
	 */
	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	/**
	 * Get the categoria.
	 * 
	 * @return categoria
	 */
	public String getCategoria() {
		return this.categoria;
	}

	/**
	 * Set the descripcion.
	 * 
	 * @param descripcion descripcion
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * Get the descripcion.
	 * 
	 * @return descripcion
	 */
	public String getDescripcion() {
		return this.descripcion;
	}

	public String getHeader() {
		return "CATEGORIAS\nid;categoria;descripción\n";
	}

	@Override
	public String toString() {
		return id + ";" + categoria + ";" + descripcion + "\n";
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Categorias other = (Categorias) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
