package schooler;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of asignatura.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AsignaturaSchooler implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** codasignatura. */
	private Integer codasignatura;

	/** nombre. */
	private String nombre;

	/** idprofesor. */
	private Integer idprofesor;

	/** The set of recibe. */
	private Set<RecibeSchooler> recibeSet;

	/**
	 * Constructor.
	 */
	public AsignaturaSchooler() {
		this.recibeSet = new HashSet<RecibeSchooler>();
	}

	/**
	 * Set the codasignatura.
	 * 
	 * @param codasignatura
	 *            codasignatura
	 */
	public void setCodasignatura(Integer codasignatura) {
		this.codasignatura = codasignatura;
	}

	/**
	 * Get the codasignatura.
	 * 
	 * @return codasignatura
	 */
	public Integer getCodasignatura() {
		return this.codasignatura;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the idprofesor.
	 * 
	 * @param idprofesor
	 *            idprofesor
	 */
	public void setIdprofesor(Integer idprofesor) {
		this.idprofesor = idprofesor;
	}

	/**
	 * Get the idprofesor.
	 * 
	 * @return idprofesor
	 */
	public Integer getIdprofesor() {
		return this.idprofesor;
	}

	/**
	 * Set the set of the recibe.
	 * 
	 * @param recibeSet
	 *            The set of recibe
	 */
	public void setRecibeSet(Set<RecibeSchooler> recibeSet) {
		this.recibeSet = recibeSet;
	}

	/**
	 * Add the recibe.
	 * 
	 * @param recibe
	 *            recibe
	 */
	public void addRecibe(RecibeSchooler recibe) {
		this.recibeSet.add(recibe);
	}

	/**
	 * Get the set of the recibe.
	 * 
	 * @return The set of recibe
	 */
	public Set<RecibeSchooler> getRecibeSet() {
		return this.recibeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codasignatura == null) ? 0 : codasignatura.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AsignaturaSchooler other = (AsignaturaSchooler) obj;
		if (codasignatura == null) {
			if (other.codasignatura != null) {
				return false;
			}
		} else if (!codasignatura.equals(other.codasignatura)) {
			return false;
		}
		return true;
	}

}
