package schooler;

import java.io.Serializable;

/**
 * Model class of profesor.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProfesorSchooler implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** idprofesor. */
	private Integer idprofesor;

	/** nif_p. */
	private String nifP;

	/** nombre. */
	private String nombre;

	/** especialidad. */
	private String especialidad;

	/**
	 * Constructor.
	 */
	public ProfesorSchooler() {
	}

	/**
	 * Set the idprofesor.
	 * 
	 * @param idprofesor
	 *            idprofesor
	 */
	public void setIdprofesor(Integer idprofesor) {
		this.idprofesor = idprofesor;
	}

	/**
	 * Get the idprofesor.
	 * 
	 * @return idprofesor
	 */
	public Integer getIdprofesor() {
		return this.idprofesor;
	}

	/**
	 * Set the nif_p.
	 * 
	 * @param nifP
	 *            nif_p
	 */
	public void setNifP(String nifP) {
		this.nifP = nifP;
	}

	/**
	 * Get the nif_p.
	 * 
	 * @return nif_p
	 */
	public String getNifP() {
		return this.nifP;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the especialidad.
	 * 
	 * @param especialidad
	 *            especialidad
	 */
	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	/**
	 * Get the especialidad.
	 * 
	 * @return especialidad
	 */
	public String getEspecialidad() {
		return this.especialidad;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idprofesor == null) ? 0 : idprofesor.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProfesorSchooler other = (ProfesorSchooler) obj;
		if (idprofesor == null) {
			if (other.idprofesor != null) {
				return false;
			}
		} else if (!idprofesor.equals(other.idprofesor)) {
			return false;
		}
		return true;
	}

}
