package schooler;

import java.io.Serializable;

/**
 * Model class of recibe.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecibeSchooler implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** alumno. */
	private AlumnoSchooler alumno;

	/** asignatura. */
	private AsignaturaSchooler asignatura;

	/** cursoescolar. */
	private String cursoescolar;

	/**
	 * Constructor.
	 */
	public RecibeSchooler() {
	}

	/**
	 * Set the alumno.
	 * 
	 * @param alumno
	 *            alumno
	 */
	public void setAlumno(AlumnoSchooler alumno) {
		this.alumno = alumno;
	}

	/**
	 * Get the alumno.
	 * 
	 * @return alumno
	 */
	public AlumnoSchooler getAlumno() {
		return this.alumno;
	}

	/**
	 * Set the asignatura.
	 * 
	 * @param asignatura
	 *            asignatura
	 */
	public void setAsignatura(AsignaturaSchooler asignatura) {
		this.asignatura = asignatura;
	}

	/**
	 * Get the asignatura.
	 * 
	 * @return asignatura
	 */
	public AsignaturaSchooler getAsignatura() {
		return this.asignatura;
	}

	/**
	 * Set the cursoescolar.
	 * 
	 * @param cursoescolar
	 *            cursoescolar
	 */
	public void setCursoescolar(String cursoescolar) {
		this.cursoescolar = cursoescolar;
	}

	/**
	 * Get the cursoescolar.
	 * 
	 * @return cursoescolar
	 */
	public String getCursoescolar() {
		return this.cursoescolar;
	}


}
